modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "architectury_example_mod"
#version = "${version}"
version = "1.0.0"
displayName = "Architectury Example Mod"
authors = "Me!"
description = '''
This is an example description! Tell everyone what your mod is about!
'''
#logoFile = ""

[[dependencies.architectury_example_mod]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.architectury_example_mod]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.architectury_example_mod]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "architectury_example_mod.mixins.json"
